name: better-barf
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - tqdm
  - termcolor
  - easydict
  - imageio
  - ipdb
  - pytorch>=1.9.0
  - pytorch-cuda=11.8
  - torchvision
  - tensorboard
  - visdom
  - matplotlib
  - scikit-video
  - trimesh
  - pyyaml
  - pip
  - gdown
  - opencv
  - pip:
    - lpips
    # - pymcubes
