name: Pylint
on:
  pull_request:
    branches:
      - main
jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Python linter
        id: pylint
        uses: docker://reasonsoftware/action-pylint:v1
